variables:
  DOCKER_IMAGE: registry.gitlab.com/partisia/dockerimages/maven-jdk9:latest

image: $DOCKER_IMAGE

run-test:
  stage: build
  script:
    - mvn test
  artifacts:
    paths:
      - core/target/site/jacoco
      - suite/spdz/target/site/jacoco
      - suite/spdz2k/target/site/jacoco
      - suite/tinytables/target/site/jacoco
      - tools/mascot/target/site/jacoco
      - tools/ot/target/site/jacoco